name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install Node 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM Packages
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Compile
      run: npm run build

    - name: Execute unit tests
      run: npm run test

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./build/cobertura-coverage.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: webpack-glsl-minify-${{github.run_number}}
        path: |
          **
          !**/node_modules/**

    - name: Publish NPM Package
      if: github.ref == 'refs/heads/master'
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
